# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b241f7ab0da39550fa75f2ac0bd0d29e56b463c42d16236f0c20d1b03d79455035486aa5e16fe9bf74be3b98c05cc86a0b1be4e6c31c8b05f707d9eb3d52744

test:
  secret_key_base: ed2f0f590d5e39bb37410745d2dd461e9b5d5ee4d123ec33d760db3c73a93320e9359910ad57b5d2f88d67f46a09217f22bbeb88019afedb61e2cba3f91c6337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
